### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
I would make a call for testers for this transition. As you can see in the old app.src, the current source is a fork I made ages ago (cf. #25) when there was database issues if I recall correctly. Testers should make sure their data is not lost.

**Comment by ericgaspar** [comment]
I have no idea how this app works. it seems to be a different app in fact

**Comment by tituspijean** [comment]
Oh I see. This package is for the Owntracks Recorder, which offers an API to send geolocation data, which stores them in a database. With this PR you are switching to the Owntracks frontend, which displays said data.

**Comment by lapineige** [comment]
So this PR switches to a different app ?

**Comment by lapineige** [comment]
!testme

**Comment by Salamandar** [comment]
!testme

**Pull request merged**
