### PR TITLE
Fixed upstream.

### LINKED ISSUE #25: Change upstream code package
### The Wish

Looks like the upstream app code is from an outdated repository.
I would like some features in more recent versions.
To be able to use more recent commands and options provided by another repository (which the developers currently use).

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.15
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.1~ynh10

### Steps to reproduce

- SSH into virtual server. 
- Try CLI command 'ocat'
- No such command etc

The new place can be found at:
[Repository](https://github.com/owntracks/recorder)

### PR DESCRIPTION
**Pull request by orhtej2**
Closes #25 

## Problem

- Autoupdater failing

## Solution

- Upstream points to proper repo.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
if i remember well, we're not using the official owntracks but a fork, and the original upstream is not compatible with it

**Comment by orhtej2** [comment]
> if i remember well, we're not using the official owntracks but a fork, and the original upstream is not compatible with it

I thought so but [manifest claims otherwise](https://github.com/YunoHost-Apps/owntracks_ynh/blob/7d5ce97d28c8a64b1531a3074f61b7bd6ea9abb6/manifest.toml#L49C1-L52C80) 🤷 

I see this actually changed in packaging v2 transition but don't want to tag random people.

**Comment by orhtej2** [comment]
>     3. Write a migration script to transition this very old and outdated package towards the actual upstream code, while preserving the data location.

This means currently released `master` is borked if you upgrade from previous version? 😬

**Comment by orhtej2** [comment]
Let's see #30...

**Comment by tituspijean** [comment]
> Let's see #30...
I have not looked at the code for a long time, but my guess is that the new upstream will be somewhat cleanly installed. It's just that the old data will be... ignored, stored in unexpected tables.

**Review by tituspijean — CHANGES_REQUESTED** [review]
We need to change upstream to https://github.com/owntracks/recorder and maybe install the front-end at the same time.

We also need to add a warning that previous location data will be lost. Let's maybe offer a SQL backup, and at best try to convert the data?

**Comment by tituspijean** [comment]
Superseded #35

**Pull request closed without merging**
